### PR TITLE
add new flags

### PR DESCRIPTION
**Pull request by Daniel-GrunbergerCA**
`RelevantImageVulnerabilitiesConfiguration` - The users configuration for relevancy scan

`ClusterProvider` - The cluster cloud provider

### CODE REVIEW

**Comment by matthyx** [comment]
how will we determine the cluster provider?

**Comment by Daniel-GrunbergerCA** [comment]
@matthyx We have it on helm-chart: https://github.com/kubescape/helm-charts/blob/main/charts/kubescape-cloud-operator/templates/_helpers.tpl#L2

**Review by dwertent — APPROVED** [review]

**Comment by dwertent** [comment]
@Daniel-GrunbergerCA I think we should merge this after you know what to do in the helm chart

**Comment by Daniel-GrunbergerCA** [comment]
https://github.com/kubescape/helm-charts/pull/222

**Pull request merged**
